name: Go
on:
  pull_request:
    branches:
      - master
jobs:

  build_run:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: |
        go build -v .

    - name: Test
      run: go test ./...

    - name: Setup DB
      run: mysql -uroot -proot -P 33060 < mysql/init.sql > out.txt

    - name: Run
      run: ./csv2sql -d todo -i ./examples

    services:
      db:
        image: mysql:5.7
        ports:
          - 33060:3306
        env:
          MYSQL_ROOT_PASSWORD: "root"
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
